spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backend_demo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # update automatically
      #jpa.hibernate.ddl-auto是hibernate的配置属性，其主要作用是：自动创建、更新、验证数据库表结构。
    show-sql: true  # show sql in dialog